import type { AppData } from "./types";

export const appData: AppData = {
  workoutPrograms: {
    pilates_beginner: {
      name: "Pilates Débutant",
      description: "Découverte douce du Pilates pour débutantes",
      duration: "25-35 min",
      difficulty: "Facile",
      color: "#ec4899",
      exercises: [
        {
          id: "pilates_warmup",
          name: "Échauffement Pilates",
          duration: "5 min",
          icon: "🌸",
          calories: 20,
          sets: 1,
          description:
            "Réveil en douceur du corps et connexion à la respiration",
          instructions: [
            "Position allongée, genoux pliés",
            "Respiration profonde - 10 cycles",
            "Basculement du bassin - 8 répétitions",
            "Étirement de la colonne vertébrale",
          ],
          imageUrl: "https://placehold.co/600x400.png",
        },
        {
          id: "pilates_hundred",
          name: "The Hundred (modifié)",
          duration: "3 min",
          icon: "💯",
          calories: 25,
          sets: 1,
          description: "Exercice signature du Pilates pour le core",
          instructions: [
            "Allongée, genoux à 90°",
            "Lever la tête et les épaules",
            "Bras tendus, pomper de haut en bas",
            "5 respirations = 10 pompages",
            "Répéter 10 fois (100 pompages total)",
          ],
          imageUrl: "https://placehold.co/600x400.png",
        },
        {
          id: "pilates_roll_up",
          name: "Roll Up progressif",
          duration: "4 min",
          icon: "🔄",
          calories: 30,
          sets: 1,
          description: "Mobilité de la colonne et renforcement abdominal",
          instructions: [
            "Allongée, bras vers le plafond",
            "Rouler vertèbre par vertèbre",
            "Étirer vers l'avant",
            "Redescendre lentement",
            "6-8 répétitions lentes",
          ],
          imageUrl: "https://placehold.co/600x400.png",
        },
        {
          id: "pilates_single_leg",
          name: "Single Leg Circle",
          duration: "6 min",
          icon: "⭕",
          calories: 35,
          sets: 1,
          description: "Stabilité du bassin et mobilité de la hanche",
          instructions: [
            "Allongée, une jambe tendue au plafond",
            "Tracer des cercles avec la jambe",
            "5 cercles dans chaque sens",
            "Changer de jambe",
            "Garder le bassin stable",
          ],
          imageUrl: "https://placehold.co/600x400.png",
        },
        {
          id: "pilates_plank",
          name: "Plank Pilates",
          duration: "4 min",
          icon: "🏗️",
          calories: 40,
          sets: 1,
          description: "Renforcement global avec focus sur l'alignement",
          instructions: [
            "Position planche sur avant-bras",
            "Maintenir 30 secondes",
            "Focus sur la respiration",
            "Répéter 4 fois avec pauses",
          ],
          imageUrl: "https://placehold.co/600x400.png",
        },
        {
          id: "pilates_stretching",
          name: "Étirements Pilates",
          duration: "8 min",
          icon: "🧘‍♀️",
          calories: 20,
          sets: 1,
          description: "Retour au calme et allongement musculaire",
          instructions: [
            "Child's pose - 2 min",
            "Étirement des fléchisseurs de hanche",
            "Twist spinal doux",
            "Savasana final - 2 min",
          ],
          imageUrl: "https://placehold.co/600x400.png",
        },
      ],
    },
    pilates_intermediate: {
      name: "Pilates Intermédiaire",
      description: "Approfondissement des techniques Pilates",
      duration: "40-50 min",
      difficulty: "Modéré",
      color: "#f97316",
      exercises: [
        {
          id: "pilates_warmup_int",
          name: "Échauffement avancé",
          duration: "8 min",
          icon: "🌸",
          calories: 35,
          sets: 1,
          description: "Préparation complète du corps",
          instructions: [
            "Respiration costale - 2 min",
            "Cat-Cow dynamique - 2 min",
            "Bird dog - 2 min chaque côté",
            "Activation des abdominaux profonds",
          ],
          imageUrl: "https://placehold.co/600x400.png",
        },
        {
          id: "pilates_teaser",
          name: "Teaser progression",
          duration: "6 min",
          icon: "⚖️",
          calories: 50,
          sets: 3,
          description: "Équilibre et force du centre",
          instructions: [
            "Assis, jambes tendues à 45°",
            "Bras parallèles aux jambes",
            "Maintenir l'équilibre",
            "Rouler jusqu'aux épaules",
            "Revenir en contrôle",
          ],
          imageUrl: "https://placehold.co/600x400.png",
        },
        {
          id: "pilates_saw",
          name: "The Saw",
          duration: "5 min",
          icon: "🪚",
          calories: 40,
          sets: 3,
          description: "Rotation spinale et étirement",
          instructions: [
            "Assis, jambes écartées",
            "Bras en croix",
            "Tourner et étirer vers l'avant",
            "Alterner droite et gauche",
            "6 répétitions de chaque côté",
          ],
          imageUrl: "https://placehold.co/600x400.png",
        },
        {
          id: "pilates_swan",
          name: "Swan Dive",
          duration: "7 min",
          icon: "🦢",
          calories: 45,
          sets: 2,
          description: "Extension de la colonne et dos",
          instructions: [
            "Sur le ventre, mains sous les épaules",
            "Lever le torse en extension",
            "Basculer d'avant en arrière",
            "Contrôler le mouvement",
            "8-10 répétitions fluides",
          ],
          imageUrl: "https://placehold.co/600x400.png",
        },
         {
          id: "pilates_corkscrew",
          name: "Corkscrew",
          duration: "6 min",
          icon: "🌀",
          calories: 50,
          sets: 2,
          description: "Mobilité et contrôle avancé",
          instructions: [
            "Allongée, jambes à 90°",
            "Tracer de grands cercles",
            "Jambes collées ensemble",
            "Contrôler avec les abdos",
            "5 cercles dans chaque sens",
          ],
          imageUrl: "https://placehold.co/600x400.png",
        },
        {
          id: "pilates_cool_down_int",
          name: "Retour au calme",
          duration: "8 min",
          icon: "🧘‍♀️",
          calories: 25,
          sets: 1,
          description: "Détente et integration",
          instructions: [
            "Mermaid stretch - 2 min chaque côté",
            "Hip flexor stretch",
            "Spinal twist allongé",
            "Relaxation finale avec respiration",
          ],
          imageUrl: "https://placehold.co/600x400.png",
        },
      ],
    },
    pilates_advanced: {
      name: "Pilates Avancé",
      description: "Pilates de niveau expert pour défis",
      duration: "55-65 min",
      difficulty: "Expert",
      color: "#7c3aed",
      exercises: [
        {
          id: "pilates_advanced_warmup",
          name: "Préparation experte",
          duration: "10 min",
          icon: "🔥",
          calories: 50,
          sets: 1,
          description: "Activation complète et mobilité",
          instructions: [
            "Footwork sur reformer virtuel",
            "Hundred complet - jambes tendues",
            "Roll over preparation",
            "Thoracic spine mobilization",
          ],
          imageUrl: "https://placehold.co/600x400.png",
        },
        {
          id: "pilates_control_balance",
          name: "Control Balance",
          duration: "8 min",
          icon: "🤸‍♀️",
          calories: 70,
          sets: 3,
          description: "Équilibre et contrôle extrême",
          instructions: [
            "Roll over jusqu'aux épaules",
            "Une jambe vers le sol",
            "Changer de jambe en l'air",
            "Maintenir l'équilibre",
            "Contrôle total du mouvement",
          ],
          imageUrl: "https://placehold.co/600x400.png",
        },
        {
          id: "pilates_boomerang",
          name: "Boomerang",
          duration: "10 min",
          icon: "🪃",
          calories: 80,
          sets: 4,
          description: "Enchaînement complexe et fluide",
          instructions: [
            "Teaser avec jambes croisées",
            "Roll over avec changement de jambes",
            "Return to teaser",
            "Dive forward avec bras",
            "Fluidité et contrôle requis",
          ],
          imageUrl: "https://placehold.co/600x400.png",
        },
        {
          id: "pilates_snake_twist",
          name: "Snake & Twist",
          duration: "12 min",
          icon: "🐍",
          calories: 85,
          sets: 3,
          description: "Force latérale et rotation",
          instructions: [
            "Side plank avec jambe levée",
            "Rotation du torse",
            "Threading the needle",
            "Maintenir la ligne latérale",
            "Alternance des côtés",
          ],
          imageUrl: "https://placehold.co/600x400.png",
        },
        {
          id: "pilates_star",
          name: "Star Preparation",
          duration: "8 min",
          icon: "⭐",
          calories: 75,
          sets: 2,
          description: "Défi ultime d'équilibre",
          instructions: [
            "Side plank sur une main",
            "Jambe et bras libres en star",
            "Pulse ups et extensions",
            "Maintenir 30 sec minimum",
            "Contrôle et stabilité maximale",
          ],
          imageUrl: "https://placehold.co/600x400.png",
        },
        {
          id: "pilates_integration",
          name: "Intégration finale",
          duration: "12 min",
          icon: "✨",
          calories: 40,
          sets: 1,
          description: "Intégration et restauration",
          instructions: [
            "Flowing sequence de tous les mouvements",
            "Emphasis sur la qualité",
            "Stretching profond",
            "Méditation en mouvement",
            "Connection corps-esprit",
          ],
          imageUrl: "https://placehold.co/600x400.png",
        },
      ],
    },
    beginner: {
      name: "Programme Débutant",
      description: "Parfait pour commencer en douceur",
      duration: "30-40 min",
      difficulty: "Facile",
      color: "#22c55e",
      exercises: [
        {
          id: "warmup",
          name: "Échauffement dynamique",
          duration: "8 min",
          icon: "🔥",
          calories: 25,
          sets: 1,
          description: "Mouvements articulaires et cardio léger",
          instructions: [
            "Rotation des épaules - 30 sec",
            "Marche sur place - 1 min",
            "Rotation des hanches - 30 sec",
            "Étirements dynamiques - 2 min",
          ],
          imageUrl: "https://placehold.co/600x400.png",
        },
        {
          id: "bodyweight",
          name: "Exercices poids du corps",
          duration: "15 min",
          icon: "🏋️",
          calories: 80,
          sets: 3,
          description: "Renforcement musculaire sans matériel",
          instructions: [
            "Squats - 3x12",
            "Pompes (genoux si besoin) - 3x8",
            "Planche - 3x30 sec",
            "Fentes alternées - 3x10 chaque jambe",
          ],
          imageUrl: "https://placehold.co/600x400.png",
        },
        {
          id: "cardio",
          name: "Cardio modéré",
          duration: "10 min",
          icon: "❤️",
          calories: 60,
          sets: 1,
          description: "Amélioration de l'endurance",
          instructions: [
            "Marche rapide ou jogging léger - 5 min",
            "Montées de genoux - 1 min",
            "Talons-fesses - 1 min",
            "Retour au calme - 3 min",
          ],
          imageUrl: "https://placehold.co/600x400.png",
        },
        {
          id: "stretch",
          name: "Étirements",
          duration: "7 min",
          icon: "🧘",
          calories: 15,
          sets: 1,
          description: "Récupération et flexibilité",
          instructions: [
            "Étirement des quadriceps - 1 min chaque jambe",
            "Étirement des ischio-jambiers - 1 min chaque jambe",
            "Étirement du dos - 2 min",
            "Relaxation finale - 1 min",
          ],
          imageUrl: "https://placehold.co/600x400.png",
        },
      ],
    },
    intermediate: {
      name: "Programme Intermédiaire",
      description: "Intensité modérée pour progresser",
      duration: "45-55 min",
      difficulty: "Modéré",
      color: "#f59e0b",
      exercises: [
        {
          id: "warmup_int",
          name: "Échauffement intensif",
          duration: "10 min",
          icon: "🔥",
          calories: 35,
          sets: 1,
          description: "Préparation complète du corps",
          instructions: [
            "Course légère sur place - 3 min",
            "Jumping jacks - 2 min",
            "Mouvements articulaires - 3 min",
            "Activation musculaire - 2 min",
          ],
          imageUrl: "https://placehold.co/600x400.png",
        },
        {
          id: "strength",
          name: "Musculation fonctionnelle",
          duration: "20 min",
          icon: "💪",
          calories: 120,
          sets: 4,
          description: "Renforcement avec intensité",
          instructions: [
            "Squats sautés - 4x15",
            "Pompes diamant - 4x10",
            "Burpees - 4x8",
            "Mountain climbers - 4x20",
            "Gainage latéral - 4x30 sec chaque côté",
          ],
          imageUrl: "https://placehold.co/600x400.png",
        },
        {
          id: "hiit",
          name: "HIIT Circuit",
          duration: "15 min",
          icon: "⚡",
          calories: 150,
          sets: 3,
          description: "Haute intensité pour brûler les graisses",
          instructions: [
            "Circuit 1: 45 sec effort / 15 sec repos",
            "Circuit 2: 40 sec effort / 20 sec repos",
            "Circuit 3: 30 sec effort / 30 sec repos",
            "Exercices: Burpees, Jump squats, High knees, Plank jacks",
          ],
          imageUrl: "https://placehold.co/600x400.png",
        },
        {
          id: "recovery",
          name: "Récupération active",
          duration: "10 min",
          icon: "🧘",
          calories: 25,
          sets: 1,
          description: "Retour au calme et étirements",
          instructions: [
            "Marche lente - 3 min",
            "Étirements profonds - 5 min",
            "Respiration contrôlée - 2 min",
          ],
          imageUrl: "https://placehold.co/600x400.png",
        },
      ],
    },
    advanced: {
      name: "Programme Avancé",
      description: "Pour les sportifs confirmés",
      duration: "60-75 min",
      difficulty: "Difficile",
      color: "#ef4444",
      exercises: [
        {
          id: "warmup_adv",
          name: "Activation complète",
          duration: "12 min",
          icon: "🔥",
          calories: 45,
          sets: 1,
          description: "Préparation intensive",
          instructions: [
            "Course d'échauffement - 5 min",
            "Mobilité dynamique - 4 min",
            "Activation neuromusculaire - 3 min",
          ],
          imageUrl: "https://placehold.co/600x400.png",
        },
        {
          id: "strength_adv",
          name: "Force et puissance",
          duration: "25 min",
          icon: "🏋️",
          calories: 180,
          sets: 5,
          description: "Développement de la force maximale",
          instructions: [
            "Squats pistol - 5x6 chaque jambe",
            "Pompes archer - 5x8 chaque bras",
            "Handstand push-ups - 5x5",
            "Muscle-ups - 5x3",
            "Dragon flag - 5x8",
          ],
          imageUrl: "https://placehold.co/600x400.png",
        },
        {
          id: "conditioning",
          name: "Conditionnement métabolique",
          duration: "20 min",
          icon: "⚡",
          calories: 220,
          sets: 4,
          description: "Endurance et résistance maximale",
          instructions: [
            "Tabata 1: Burpees - 4 min",
            "Tabata 2: Thrusters - 4 min",
            "Tabata 3: Box jumps - 4 min",
            "Finisher: Sprint intervals - 8 min",
          ],
          imageUrl: "https://placehold.co/600x400.png",
        },
        {
          id: "recovery_adv",
          name: "Récupération profonde",
          duration: "18 min",
          icon: "🧘",
          calories: 35,
          sets: 1,
          description: "Régénération complète",
          instructions: ["Yoga flow - 8 min", "Étirements PNF - 6 min", "Méditation - 4 min"],
          imageUrl: "https://placehold.co/600x400.png",
        },
      ],
    },
  },
  nutritionData: {
    recipes: {
      breakfast: [
        {
          id: "avocado_toast",
          name: "Toast à l'avocat protéiné",
          emoji: "🥑🍞",
          time: "10 min",
          difficulty: "Facile",
          calories: 320,
          macros: { protein: 15, carbs: 28, fat: 18 },
          ingredients: [
            "1 tranche de pain complet",
            "1/2 avocat mûr",
            "1 œuf bio",
            "1 c.à.s. de graines de tournesol",
            "Sel, poivre, citron",
          ],
          instructions: [
            "Faire griller le pain complet",
            "Écraser l'avocat avec une fourchette",
            "Ajouter citron, sel et poivre à l'avocat",
            "Cuire l'œuf au plat ou poché",
            "Tartiner l'avocat sur le pain",
            "Déposer l'œuf et les graines",
          ],
          tips: "Choisir un avocat bien mûr pour une texture crémeuse",
        },
        {
          id: "protein_smoothie",
          name: "Smoothie protéiné aux fruits",
          emoji: "🥤🍓",
          time: "5 min",
          difficulty: "Facile",
          calories: 280,
          macros: { protein: 25, carbs: 35, fat: 8 },
          ingredients: [
            "1 banane",
            "150g de fruits rouges",
            "1 scoop de protéine vanille",
            "200ml de lait d'amande",
            "1 c.à.s. de beurre d'amande",
          ],
          instructions: [
            "Mettre tous les ingrédients dans le blender",
            "Mixer pendant 60 secondes",
            "Ajouter des glaçons si désiré",
            "Servir immédiatement",
          ],
          tips: "Préparer les fruits la veille et les congeler pour plus de fraîcheur",
        },
      ],
      lunch: [
        {
          id: "quinoa_bowl",
          name: "Bowl de quinoa aux légumes",
          emoji: "🥗🌈",
          time: "25 min",
          difficulty: "Modéré",
          calories: 450,
          macros: { protein: 18, carbs: 55, fat: 16 },
          ingredients: [
            "100g de quinoa",
            "150g de brocolis",
            "1 carotte",
            "50g de pois chiches",
            "1/4 d'avocat",
            "Vinaigrette tahini",
          ],
          instructions: [
            "Cuire le quinoa selon les instructions",
            "Cuire les brocolis à la vapeur",
            "Râper la carotte",
            "Réchauffer les pois chiches",
            "Assembler dans un bol",
            "Ajouter l'avocat et la vinaigrette",
          ],
          tips: "Préparer plusieurs portions à l'avance pour la semaine",
        },
      ],
      dinner: [
        {
          id: "salmon_veggies",
          name: "Saumon grillé aux légumes",
          emoji: "🐟🥬",
          time: "30 min",
          difficulty: "Modéré",
          calories: 420,
          macros: { protein: 35, carbs: 20, fat: 22 },
          ingredients: [
            "150g de filet de saumon",
            "200g de légumes verts",
            "1 courgette",
            "1 c.à.s. d'huile d'olive",
            "Herbes de Provence",
            "Citron",
          ],
          instructions: [
            "Préchauffer le four à 200°C",
            "Couper les légumes en morceaux",
            "Assaisonner le saumon",
            "Cuire le saumon 15 min au four",
            "Faire revenir les légumes",
            "Servir avec du citron",
          ],
          tips: "Choisir du saumon sauvage pour plus d'oméga-3",
        },
      ],
      snacks: [
        {
          id: "energy_balls",
          name: "Energy balls aux dattes",
          emoji: "⚡🥎",
          time: "15 min",
          difficulty: "Facile",
          calories: 80,
          macros: { protein: 3, carbs: 12, fat: 4 },
          ingredients: [
            "100g de dattes dénoyautées",
            "50g d'amandes",
            "2 c.à.s. de cacao",
            "1 c.à.s. de graines de chia",
            "Noix de coco râpée",
          ],
          instructions: [
            "Mixer les dattes et amandes",
            "Ajouter cacao et chia",
            "Former des petites boules",
            "Rouler dans la noix de coco",
            "Réfrigérer 30 min",
          ],
          tips: "Se conservent 1 semaine au frigo dans une boîte hermétique",
        },
      ],
    },
    waterTracker: {
      dailyGoal: 2500,
      currentIntake: 0,
      glasses: [
        { time: "07:00", amount: 250, completed: false },
        { time: "09:00", amount: 250, completed: false },
        { time: "11:00", amount: 250, completed: false },
        { time: "13:00", amount: 250, completed: false },
        { time: "15:00", amount: 250, completed: false },
        { time: "17:00", amount: 250, completed: false },
        { time: "19:00", amount: 250, completed: false },
        { time: "21:00", amount: 250, completed: false },
      ],
    },
    macroTargets: {
      calories: 1800,
      protein: 130,
      carbs: 200,
      fat: 70,
    },
  },
  mentalExercises: [
    {
      id: "breathing_478",
      name: "Respiration 4-7-8",
      description:
        "Technique anti-stress immédiate pour calmer le système nerveux",
      duration: "5 min",
      icon: "🫁",
      category: "respiration",
      difficulty: "Facile",
      benefits: [
        "Réduit le stress",
        "Améliore le sommeil",
        "Calme l'anxiété",
      ],
      instructions: [
        "Asseyez-vous confortablement, dos droit",
        "Expirez complètement par la bouche",
        "Inspirez par le nez en comptant jusqu'à 4",
        "Retenez votre souffle en comptant jusqu'à 7",
        "Expirez par la bouche en comptant jusqu'à 8",
        "Répétez ce cycle 4 fois pour commencer",
      ],
      tips: "Pratiquez cette technique le soir avant de dormir",
    },
    {
      id: "meditation",
      name: "Méditation de pleine conscience",
      description:
        "Méditation guidée pour développer la présence et la sérénité",
      duration: "10 min",
      icon: "🧘",
      category: "meditation",
      difficulty: "Modéré",
      benefits: [
        "Améliore la concentration",
        "Réduit l'anxiété",
        "Développe la sérénité",
      ],
      instructions: [
        "Trouvez un endroit calme et confortable",
        "Asseyez-vous en tailleur ou sur une chaise",
        "Fermez les yeux et respirez naturellement",
        "Concentrez-vous sur votre respiration",
        "Quand votre esprit divague, revenez à la respiration",
        "Terminez en prenant conscience de votre corps",
      ],
      tips: "Commencez par 5 minutes et augmentez progressivement",
    },
    {
      id: "body_scan",
      name: "Scan corporel relaxant",
      description: "Technique de relaxation profonde par exploration du corps",
      duration: "15 min",
      icon: "🫧",
      category: "relaxation",
      difficulty: "Facile",
      benefits: [
        "Relâche les tensions",
        "Améliore la conscience corporelle",
        "Favorise l'endormissement",
      ],
      instructions: [
        "Allongez-vous confortablement",
        "Commencez par vos orteils",
        "Portez attention à chaque partie du corps",
        "Relâchez consciemment les tensions",
        "Remontez progressivement jusqu'à la tête",
        "Prenez quelques respirations profondes pour finir",
      ],
      tips: "Parfait à pratiquer le soir dans votre lit",
    },
    {
      id: "gratitude",
      name: "Pratique de gratitude",
      description: "Exercice pour cultiver la reconnaissance et la joie",
      duration: "8 min",
      icon: "🙏",
      category: "bien-etre",
      difficulty: "Facile",
      benefits: [
        "Améliore l'humeur",
        "Développe l'optimisme",
        "Renforce les relations",
      ],
      instructions: [
        "Prenez un carnet ou votre téléphone",
        "Listez 3 choses pour lesquelles vous êtes reconnaissante",
        "Décrivez pourquoi chaque élément est important",
        "Ressentez l'émotion de gratitude",
        "Partagez votre gratitude avec quelqu'un si possible",
      ],
      tips: "Pratiquez chaque matin pour commencer la journée positivement",
    },
  ],
};
